import { JarKey } from '@rumbelo/contracts';

type Seed = {
    key: string;
    name: string;
    matchValue: string;
    aliases: string[];
    mcc: string | null;
    jarKey: JarKey;
    categoryTemplateKey: string;
};

const necessities = JarKey.NECESSITIES;
const play = JarKey.PLAY;
const education = JarKey.EDUCATION;
const give = JarKey.GIVE;

/**
 * Merchant matchbook for inbox rules, expense vendor chips, and future Open Banking.
 * NL-first spine: a few top vendors per high-frequency spend category.
 * Debt lenders live on debt presets (suggestedLenders) — not here.
 * `aliases` cover noisy bank descriptors; `mcc` is optional ISO 18245.
 */
export const MERCHANT_PRESET_SEED: readonly Seed[] = [
    // ── GROCERIES ──────────────────────────────────────────────────────────
    {
        key: 'ALBERT_HEIJN',
        name: 'Albert Heijn',
        matchValue: 'Albert Heijn',
        aliases: ['Albert Heijn', 'AH ', 'AH.nl', 'AH TO GO', 'AH to go'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
    },
    {
        key: 'JUMBO',
        name: 'Jumbo',
        matchValue: 'Jumbo',
        aliases: ['Jumbo', 'JUMBO SUPERMARKT'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
    },
    {
        key: 'LIDL',
        name: 'Lidl',
        matchValue: 'Lidl',
        aliases: ['Lidl', 'LIDL NL'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
    },
    {
        key: 'PLUS',
        name: 'PLUS',
        matchValue: 'PLUS',
        aliases: ['PLUS supermarket', 'Plus Supermarkt'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
    },
    {
        key: 'DIRK',
        name: 'Dirk',
        matchValue: 'Dirk',
        aliases: ['Dirk', 'DIRK VAN DEN BROEK', 'Dirk vd Broek'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
    },
    {
        key: 'ALDI',
        name: 'Aldi',
        matchValue: 'Aldi',
        aliases: ['Aldi', 'ALDI NL', 'ALDI INKOOP'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
    },
    {
        key: 'SPAR',
        name: 'Spar',
        matchValue: 'Spar',
        aliases: ['Spar', 'SPAR NL', 'SPAR CITY'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
    },
    {
        key: 'CRISP',
        name: 'Crisp',
        matchValue: 'Crisp',
        aliases: ['Crisp', 'CRISP NL', 'Crisp B.V.'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
    },

    // ── TRANSPORT ──────────────────────────────────────────────────────────
    {
        key: 'NS',
        name: 'NS',
        matchValue: 'NS ',
        aliases: ['NS ', 'NS Groep', 'Nederlandse Spoorwegen', 'OV-chipkaart NS'],
        mcc: '4111',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
    },
    {
        key: 'GVB',
        name: 'GVB',
        matchValue: 'GVB',
        aliases: ['GVB', 'GVB Amsterdam', 'Gemeente Vervoerbedrijf'],
        mcc: '4111',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
    },
    {
        key: 'RET',
        name: 'RET',
        matchValue: 'RET',
        aliases: ['RET', 'RET Rotterdam', 'RET OV'],
        mcc: '4111',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
    },
    {
        key: 'SHELL',
        name: 'Shell',
        matchValue: 'Shell',
        aliases: ['Shell', 'SHELL NL', 'Shell Station'],
        mcc: '5541',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
    },
    {
        key: 'BP',
        name: 'BP',
        matchValue: 'BP ',
        aliases: ['BP ', 'BP Station', 'BP EXPRESS'],
        mcc: '5541',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
    },
    {
        key: 'TOTALENERGIES',
        name: 'TotalEnergies',
        matchValue: 'TotalEnergies',
        aliases: ['TotalEnergies', 'TOTAL ', 'Total NL', 'TOTALEnergies'],
        mcc: '5541',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
    },
    {
        key: 'UBER',
        name: 'Uber',
        matchValue: 'Uber',
        aliases: ['Uber', 'UBER BV', 'UBER *TRIP', 'UBER TRIP'],
        mcc: '4121',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
    },
    {
        key: 'ANWB',
        name: 'ANWB',
        matchValue: 'ANWB',
        aliases: ['ANWB', 'ANWB B.V.', 'ANWB Wegenwacht'],
        mcc: '5533',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
    },

    // ── UTILITIES ──────────────────────────────────────────────────────────
    {
        key: 'VATTENFALL',
        name: 'Vattenfall',
        matchValue: 'Vattenfall',
        aliases: ['Vattenfall', 'VATTENFALL NL', 'Nuon'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
    },
    {
        key: 'ENECO',
        name: 'Eneco',
        matchValue: 'Eneco',
        aliases: ['Eneco', 'ENECO BV', 'Eneco Energy'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
    },
    {
        key: 'ESSENT',
        name: 'Essent',
        matchValue: 'Essent',
        aliases: ['Essent', 'ESSENT NL', 'Essent Retail'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
    },
    {
        key: 'WATERNET',
        name: 'Waternet',
        matchValue: 'Waternet',
        aliases: ['Waternet', 'WATERNET', 'Waterschap'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
    },

    // ── HOUSING ────────────────────────────────────────────────────────────
    {
        key: 'VESTIA',
        name: 'Vestia',
        matchValue: 'Vestia',
        aliases: ['Vestia', 'VESTIA WONEN'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
    },
    {
        key: 'YOMERE',
        name: 'Ymere',
        matchValue: 'Ymere',
        aliases: ['Ymere', 'YMERE'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
    },
    {
        key: 'IKEA',
        name: 'IKEA',
        matchValue: 'IKEA',
        aliases: ['IKEA', 'IKEA NL', 'IKEA Nederland'],
        mcc: '5712',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
    },

    // ── INSURANCE ──────────────────────────────────────────────────────────
    {
        key: 'ACHMEA',
        name: 'Achmea',
        matchValue: 'Achmea',
        aliases: ['Achmea', 'ACHMEA BV'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
    },
    {
        key: 'CENTRAAL_BEHEER',
        name: 'Centraal Beheer',
        matchValue: 'Centraal Beheer',
        aliases: ['Centraal Beheer', 'CENTRAAL BEHEER', 'CB Achmea'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
    },
    {
        key: 'INTERPOLIS',
        name: 'Interpolis',
        matchValue: 'Interpolis',
        aliases: ['Interpolis', 'INTERPOLIS'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
    },
    {
        key: 'OHRA',
        name: 'OHRA',
        matchValue: 'OHRA',
        aliases: ['OHRA', 'OHRA Verzekeringen'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
    },

    // ── SUBSCRIPTIONS ──────────────────────────────────────────────────────
    {
        key: 'VODAFONE',
        name: 'Vodafone',
        matchValue: 'Vodafone',
        aliases: ['Vodafone', 'VODAFONE NL', 'VodafoneZiggo'],
        mcc: '4814',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
    },
    {
        key: 'KPN',
        name: 'KPN',
        matchValue: 'KPN',
        aliases: ['KPN', 'KPN BV', 'KPN Mobiel'],
        mcc: '4814',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
    },
    {
        key: 'ZIGGO',
        name: 'Ziggo',
        matchValue: 'Ziggo',
        aliases: ['Ziggo', 'ZIGGO BV', 'VodafoneZiggo'],
        mcc: '4899',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
    },
    {
        key: 'ODIDO',
        name: 'Odido',
        matchValue: 'Odido',
        aliases: ['Odido', 'ODIDO', 'T-Mobile NL', 'T-Mobile Netherlands'],
        mcc: '4814',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
    },
    {
        key: 'APPLE',
        name: 'Apple',
        matchValue: 'Apple',
        aliases: ['Apple', 'APPLE.COM', 'APPLE.COM/BILL', 'Apple Services'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
    },
    {
        key: 'GOOGLE',
        name: 'Google',
        matchValue: 'Google',
        aliases: ['Google', 'GOOGLE *', 'Google Payment', 'GOOGLE PLAY'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
    },

    // ── CARE ───────────────────────────────────────────────────────────────
    {
        key: 'ETOS',
        name: 'Etos',
        matchValue: 'Etos',
        aliases: ['Etos', 'ETOS BV'],
        mcc: '5912',
        jarKey: necessities,
        categoryTemplateKey: 'CARE',
    },
    {
        key: 'KRUIDVAT',
        name: 'Kruidvat',
        matchValue: 'Kruidvat',
        aliases: ['Kruidvat', 'KRUIDVAT'],
        mcc: '5912',
        jarKey: necessities,
        categoryTemplateKey: 'CARE',
    },
    {
        key: 'DA',
        name: 'DA',
        matchValue: 'DA ',
        aliases: ['DA Drogisterij', 'DA ', 'D.A. '],
        mcc: '5912',
        jarKey: necessities,
        categoryTemplateKey: 'CARE',
    },
    {
        key: 'HOLLAND_AND_BARRETT',
        name: 'Holland & Barrett',
        matchValue: 'Holland & Barrett',
        aliases: ['Holland & Barrett', 'Holland and Barrett', 'H&B '],
        mcc: '5499',
        jarKey: necessities,
        categoryTemplateKey: 'CARE',
    },

    // ── PETS ───────────────────────────────────────────────────────────────
    {
        key: 'ZOO_PLUS',
        name: 'Zooplus',
        matchValue: 'Zooplus',
        aliases: ['Zooplus', 'ZOOPLUS', 'bitiba'],
        mcc: '5995',
        jarKey: necessities,
        categoryTemplateKey: 'PETS',
    },
    {
        key: 'PETSPLANET',
        name: 'Pets Place',
        matchValue: 'Pets Place',
        aliases: ['Pets Place', 'PETS PLACE', 'PetsPlace'],
        mcc: '5995',
        jarKey: necessities,
        categoryTemplateKey: 'PETS',
    },

    // ── BANKING ────────────────────────────────────────────────────────────
    {
        key: 'ING',
        name: 'ING',
        matchValue: 'ING',
        aliases: ['ING Bank', 'ING BANK NV', 'ING '],
        mcc: '6012',
        jarKey: necessities,
        categoryTemplateKey: 'BANKING',
    },
    {
        key: 'ABN_AMRO',
        name: 'ABN AMRO',
        matchValue: 'ABN AMRO',
        aliases: ['ABN AMRO', 'ABNAMRO', 'ABN-AMRO'],
        mcc: '6012',
        jarKey: necessities,
        categoryTemplateKey: 'BANKING',
    },
    {
        key: 'RABOBANK',
        name: 'Rabobank',
        matchValue: 'Rabobank',
        aliases: ['Rabobank', 'RABOBANK', 'Coöperatieve Rabobank'],
        mcc: '6012',
        jarKey: necessities,
        categoryTemplateKey: 'BANKING',
    },
    {
        key: 'BUNQ',
        name: 'bunq',
        matchValue: 'bunq',
        aliases: ['bunq', 'BUNQ BV', 'bunq B.V.'],
        mcc: '6012',
        jarKey: necessities,
        categoryTemplateKey: 'BANKING',
    },

    // ── TAXES & GOVERNMENT ─────────────────────────────────────────────────
    {
        key: 'BELASTINGDIENST',
        name: 'Belastingdienst',
        matchValue: 'Belastingdienst',
        aliases: ['Belastingdienst', 'BELASTINGDIENST', 'Belasting Dienst', 'Tax and Customs'],
        mcc: '9311',
        jarKey: necessities,
        categoryTemplateKey: 'TAXES',
    },
    {
        key: 'DOUANE',
        name: 'Douane',
        matchValue: 'Douane',
        aliases: ['Douane', 'DOUANE NL', 'Customs NL'],
        mcc: '9311',
        jarKey: necessities,
        categoryTemplateKey: 'TAXES',
    },
    {
        key: 'DUO',
        name: 'DUO',
        matchValue: 'DUO',
        aliases: ['DUO', 'DUO IB-Groep', 'Dienst Uitvoering Onderwijs'],
        mcc: '9311',
        jarKey: necessities,
        categoryTemplateKey: 'TAXES',
    },
    {
        key: 'RDW',
        name: 'RDW',
        matchValue: 'RDW',
        aliases: ['RDW', 'RDW.nl', 'Rijksdienst voor het Wegverkeer'],
        mcc: '9399',
        jarKey: necessities,
        categoryTemplateKey: 'TAXES',
    },
    {
        key: 'CBR',
        name: 'CBR',
        matchValue: 'CBR',
        aliases: ['CBR', 'CBR.nl', 'Centraal Bureau Rijvaardigheid'],
        mcc: '9399',
        jarKey: necessities,
        categoryTemplateKey: 'TAXES',
    },
    {
        key: 'UWV',
        name: 'UWV',
        matchValue: 'UWV',
        aliases: ['UWV', 'UWV NL', 'Uitvoeringsinstituut Werknemersverzekeringen'],
        mcc: '9399',
        jarKey: necessities,
        categoryTemplateKey: 'TAXES',
    },
    {
        key: 'SVB',
        name: 'SVB',
        matchValue: 'SVB',
        aliases: ['SVB', 'Sociale Verzekeringsbank'],
        mcc: '9399',
        jarKey: necessities,
        categoryTemplateKey: 'TAXES',
    },
    {
        key: 'KADASTER',
        name: 'Kadaster',
        matchValue: 'Kadaster',
        aliases: ['Kadaster', 'KADASTER', 'Het Kadaster'],
        mcc: '9399',
        jarKey: necessities,
        categoryTemplateKey: 'TAXES',
    },

    // ── FINES & TICKETS ────────────────────────────────────────────────────
    {
        key: 'CJIB',
        name: 'CJIB',
        matchValue: 'CJIB',
        aliases: ['CJIB', 'Centraal Justitieel Incassobureau', 'CJIB Verkeersboete', 'CJIB Boete'],
        mcc: '9222',
        jarKey: necessities,
        categoryTemplateKey: 'FINES',
    },
    {
        key: 'POLITIE',
        name: 'Politie',
        matchValue: 'Politie',
        aliases: ['Politie', 'POLITIE NL', 'Nationale Politie', 'Parket'],
        mcc: '9222',
        jarKey: necessities,
        categoryTemplateKey: 'FINES',
    },
    {
        key: 'OM',
        name: 'Openbaar Ministerie',
        matchValue: 'Openbaar Ministerie',
        aliases: ['Openbaar Ministerie', 'OM ', 'Parket OM'],
        mcc: '9222',
        jarKey: necessities,
        categoryTemplateKey: 'FINES',
    },
    {
        key: 'GEMEENTE_BOETE',
        name: 'Gemeente (boete)',
        matchValue: 'Naheffingsaanslag',
        aliases: [
            'Nahheffingsaanslag',
            'Naheffingsaanslag',
            'Parkeerboete',
            'Fiscalisatie',
            'Gemeentelijke boete',
            'Parkeernahheffing',
            'Parkeernaheffing',
        ],
        mcc: '9222',
        jarKey: necessities,
        categoryTemplateKey: 'FINES',
    },
    {
        key: 'YELLOWBRICK_FINE',
        name: 'Yellowbrick',
        matchValue: 'Yellowbrick',
        aliases: ['Yellowbrick', 'YELLOWBRICK', 'YB Parking'],
        mcc: '7523',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
    },
    {
        key: 'PARKMOBILE',
        name: 'Parkmobile',
        matchValue: 'Parkmobile',
        aliases: ['Parkmobile', 'PARKMOBILE', 'Park Mobile'],
        mcc: '7523',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
    },

    // ── FAMILY ─────────────────────────────────────────────────────────────
    {
        key: 'PRENATAL',
        name: 'Prenatal',
        matchValue: 'Prenatal',
        aliases: ['Prenatal', 'PRÉNATAL', 'Prenatal NL'],
        mcc: '5641',
        jarKey: necessities,
        categoryTemplateKey: 'FAMILY',
    },
    {
        key: 'ZEEMAN',
        name: 'Zeeman',
        matchValue: 'Zeeman',
        aliases: ['Zeeman', 'ZEEMAN TEXTIEL'],
        mcc: '5651',
        jarKey: necessities,
        categoryTemplateKey: 'FAMILY',
    },

    // ── BNPL (expense + debt lenders) ──────────────────────────────────────
    {
        key: 'KLARNA',
        name: 'Klarna',
        matchValue: 'Klarna',
        aliases: ['Klarna', 'KLARNA*', 'Klarna Bank'],
        mcc: '5999',
        jarKey: play,
        categoryTemplateKey: 'HOBBIES',
    },
    {
        key: 'AFTERPAY',
        name: 'Afterpay / Riverty',
        matchValue: 'Afterpay',
        aliases: ['Afterpay', 'Riverty', 'AFTERPAY', 'RIVERTY'],
        mcc: '5999',
        jarKey: play,
        categoryTemplateKey: 'HOBBIES',
    },

    // ── MEDIA ──────────────────────────────────────────────────────────────
    {
        key: 'SPOTIFY',
        name: 'Spotify',
        matchValue: 'Spotify',
        aliases: ['Spotify', 'SPOTIFY AB', 'Spotify P', 'SPOTIFY*'],
        mcc: '4899',
        jarKey: play,
        categoryTemplateKey: 'MEDIA',
    },
    {
        key: 'NETFLIX',
        name: 'Netflix',
        matchValue: 'Netflix',
        aliases: ['Netflix', 'NETFLIX.COM', 'NETFLIX COM'],
        mcc: '4899',
        jarKey: play,
        categoryTemplateKey: 'MEDIA',
    },
    {
        key: 'DISNEY_PLUS',
        name: 'Disney+',
        matchValue: 'Disney',
        aliases: ['Disney+', 'Disney Plus', 'DISNEYPLUS', 'Disney*'],
        mcc: '4899',
        jarKey: play,
        categoryTemplateKey: 'MEDIA',
    },
    {
        key: 'VIAPLAY',
        name: 'Viaplay',
        matchValue: 'Viaplay',
        aliases: ['Viaplay', 'VIAPLAY', 'Viaplay NL'],
        mcc: '4899',
        jarKey: play,
        categoryTemplateKey: 'MEDIA',
    },
    {
        key: 'PRIME_VIDEO',
        name: 'Prime Video',
        matchValue: 'Prime Video',
        aliases: ['Prime Video', 'AMAZON PRIME', 'AmazonPrime', 'Prime Video*'],
        mcc: '4899',
        jarKey: play,
        categoryTemplateKey: 'MEDIA',
    },
    {
        key: 'YOUTUBE_PREMIUM',
        name: 'YouTube Premium',
        matchValue: 'YouTube',
        aliases: ['YouTube Premium', 'YOUTUBEPREMIUM', 'Google YouTube'],
        mcc: '4899',
        jarKey: play,
        categoryTemplateKey: 'MEDIA',
    },

    // ── EATING_OUT ─────────────────────────────────────────────────────────
    {
        key: 'THUISBEZORGD',
        name: 'Thuisbezorgd',
        matchValue: 'Thuisbezorgd',
        aliases: ['Thuisbezorgd', 'Just Eat', 'JE*THUISBEZORGD'],
        mcc: '5812',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
    },
    {
        key: 'UBER_EATS',
        name: 'Uber Eats',
        matchValue: 'Uber Eats',
        aliases: ['Uber Eats', 'UBER *EATS', 'UBEREATS'],
        mcc: '5812',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
    },
    {
        key: 'STARBUCKS',
        name: 'Starbucks',
        matchValue: 'Starbucks',
        aliases: ['Starbucks', 'STARBUCKS', 'SBUX'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
    },
    {
        key: 'BAGELS_AND_BEANS',
        name: 'Bagels & Beans',
        matchValue: 'Bagels & Beans',
        aliases: ['Bagels & Beans', 'Bagels and Beans', 'B&B Coffee'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
    },
    {
        key: 'MCDONALDS',
        name: "McDonald's",
        matchValue: 'McDonald',
        aliases: ["McDonald's", 'McDonalds', 'MCDONALDS', 'Mc Donalds'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
    },
    {
        key: 'BURGER_KING',
        name: 'Burger King',
        matchValue: 'Burger King',
        aliases: ['Burger King', 'BURGER KING', 'BK '],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
    },

    // ── HOBBIES ────────────────────────────────────────────────────────────
    {
        key: 'BOL',
        name: 'bol.com',
        matchValue: 'bol.com',
        aliases: ['bol.com', 'BOL.COM', 'Bol Com', 'BOL COM BV'],
        mcc: '5399',
        jarKey: play,
        categoryTemplateKey: 'HOBBIES',
    },
    {
        key: 'AMAZON',
        name: 'Amazon',
        matchValue: 'Amazon',
        aliases: ['Amazon', 'AMAZON EU', 'AMZN', 'Amazon.nl', 'AMAZON PAYMENTS'],
        mcc: '5399',
        jarKey: play,
        categoryTemplateKey: 'HOBBIES',
    },
    {
        key: 'COOLBLUE',
        name: 'Coolblue',
        matchValue: 'Coolblue',
        aliases: ['Coolblue', 'COOLBLUE', 'Coolblue BV'],
        mcc: '5732',
        jarKey: play,
        categoryTemplateKey: 'HOBBIES',
    },
    {
        key: 'MEDIAMARKT',
        name: 'MediaMarkt',
        matchValue: 'MediaMarkt',
        aliases: ['MediaMarkt', 'MEDIA MARKT', 'Media Markt'],
        mcc: '5732',
        jarKey: play,
        categoryTemplateKey: 'HOBBIES',
    },

    // ── SPORT ──────────────────────────────────────────────────────────────
    {
        key: 'BASIC_FIT',
        name: 'Basic-Fit',
        matchValue: 'Basic-Fit',
        aliases: ['Basic-Fit', 'Basic Fit', 'BASICFIT', 'BasicFit'],
        mcc: '7997',
        jarKey: play,
        categoryTemplateKey: 'SPORT',
    },
    {
        key: 'SPORTCITY',
        name: 'SportCity',
        matchValue: 'SportCity',
        aliases: ['SportCity', 'SPORTCITY', 'Sport City'],
        mcc: '7997',
        jarKey: play,
        categoryTemplateKey: 'SPORT',
    },
    {
        key: 'DECATHLON',
        name: 'Decathlon',
        matchValue: 'Decathlon',
        aliases: ['Decathlon', 'DECATHLON NL'],
        mcc: '5941',
        jarKey: play,
        categoryTemplateKey: 'SPORT',
    },

    // ── EDUCATION ──────────────────────────────────────────────────────────
    {
        key: 'BRUNA',
        name: 'Bruna',
        matchValue: 'Bruna',
        aliases: ['Bruna', 'BRUNA NL', 'Bruna Boeken'],
        mcc: '5942',
        jarKey: education,
        categoryTemplateKey: 'BOOKS',
    },
    {
        key: 'UDEMY',
        name: 'Udemy',
        matchValue: 'Udemy',
        aliases: ['Udemy', 'UDEMY'],
        mcc: '8299',
        jarKey: education,
        categoryTemplateKey: 'COURSES',
    },
    {
        key: 'COURSERA',
        name: 'Coursera',
        matchValue: 'Coursera',
        aliases: ['Coursera', 'COURSERA'],
        mcc: '8299',
        jarKey: education,
        categoryTemplateKey: 'COURSES',
    },

    // ── GIVE ───────────────────────────────────────────────────────────────
    {
        key: 'GIRO555',
        name: 'Giro555',
        matchValue: 'Giro555',
        aliases: ['Giro555', 'GIRO 555', 'SHO Giro555'],
        mcc: '8398',
        jarKey: give,
        categoryTemplateKey: 'DONATIONS',
    },
    {
        key: 'KWF',
        name: 'KWF',
        matchValue: 'KWF',
        aliases: ['KWF', 'KWF Kankerbestrijding'],
        mcc: '8398',
        jarKey: give,
        categoryTemplateKey: 'DONATIONS',
    },
    {
        key: 'UNICEF',
        name: 'Unicef',
        matchValue: 'Unicef',
        aliases: ['Unicef', 'UNICEF NL', 'UNICEF Nederland'],
        mcc: '8398',
        jarKey: give,
        categoryTemplateKey: 'DONATIONS',
    },
    {
        key: 'BLOOMON',
        name: 'Bloomon',
        matchValue: 'Bloomon',
        aliases: ['Bloomon', 'BLOOMON'],
        mcc: '5992',
        jarKey: give,
        categoryTemplateKey: 'GIFTS',
    },
] as const;
